# create a patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "YOYO HONEY SINGH",
  "email": "SDFSDFSFSDF@gmail.com",
  "address": "123 Masdfdsfin Street, New Delhi",
  "dateOfBirth": "1995-08-15",
  "registeredDate": "2025-11-25"
}
