# create a patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "BROCK LESNER",
  "email": "brocklest@gmail.com",
  "address": "WWE WRESTLEMANIA",
  "dateOfBirth": "1995-08-15",
  "registeredDate": "2025-11-25"
}
