PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
    "address": "SADD PIND PUNJAB",
    "dateOfBirth": "1987-10-10",
    "email": "sophia.clark@example.com",
    "name": "DILJJIT DOSANJH",
  "registeredDate": "2025-11-25"
}